"""Custom exception hierarchy.

Responsibilities:
- Defines all project-specific exceptions in one place.
- Hierarchy: AgentError (base) -> ToolError, LLMError, ApprovalDeniedError, ConfigError.
- Enables precise except clauses at each layer without catching overly broad exceptions.
- No logic — exception class definitions only.
"""


class AgentError(Exception): ...
class ToolError(AgentError): ...
class LLMError(AgentError): ...
class ApprovalDeniedError(AgentError): ...
class ConfigError(AgentError): ...
class ToolNotFoundError(ToolError): ...
class ToolExecutionError(ToolError): ...
